### ISSUE TITLE
About cvDestroyWindow()!

### ISSUE THREAD

**Issue by jychoi415** [NoNamedSelfDriveing/openCV_Tutorial#8]
Fuzer push good sources.
I appreciate about it. 
It helps me understand about OpenCV.

Anyway, I want to advice little bit in your source.
All of your source include 'cvDestroyWindow()'.
You know, It is a function of closing Window.
You have to use it, but you use in wrong way.
'cvDestroyWindow()' is  C language function.
C++ language function of it is 'destroyWindow()'.
Therefore, I think you should use 'destroyWindow()' instead of 'cvDestroyWindow()'.

**Comment by ghost** [comment]
Hello! 'ayunran4'. I wanna say to you 2 things.

  First, The sources in master and managed by FuZer.
but, It's in my branch(potato) and I wrote the lines myself.
  Second, It(master branch) reflects in my source now. 

I appreciate to your advise. It helps me for my study of OpenCV and programming language.

**Comment by jychoi415** [comment]
Unfortunately, I can't understand what you said.
Especially, "The sources in master and managed by FuZer"?

Where is verb in that sentense?
Please insert verb and then response again.

**Comment by FuZer** [comment]
"FuZer" branch was merged with master.
Because I have to manage master branch.
when someone push new sources, then I described and make *.md file for that
and push to master branch.

**Comment by ghost** [comment]
The source's in master branch and managed by FuZer.
But the source's wrote by myself.

Therefore, That's my fault.
